[project]
name = "analysis_tools"
version = "0.1.0"
description = "Tools for WCTE Analysis"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"